<form name="add_plant" class="pop-up" action="controllers/garden.php" method="POST" enctype="multipart/form-data" style="display:none;">
    <input type="hidden" name="action" value="add_plant" />
    <input type="hidden" name="coord_x" />
    <input type="hidden" name="coord_y" />
    <h2><?= $T->__("Add a plant") ?></h2>
    <div class="plant">
        <div class="row"><label for="add_plant_description"><?= $T->__("Description") ?></label><input type="textarea" name="description" id="add_plant_description"></div>
        <div class="row"><label for="add_plant_image"><?= $T->__("Image") ?></label><input type="file" accept="image/jpeg" name="image" id="add_plant_image"></div>
        <div class="select" id="slct_species">
            <input type="hidden" name="species_id" />
            <div class="option selected" data-value="null"><?= $T->__("New species") ?></div>
            <?php foreach($fm->user->garden->species as $id => $species): ?>
            <div class="option" data-value="<?= $id ?>"><?= $species->get_name() ?></div>
            <?php endforeach; ?>
        </div>
    </div>
    <div class="species">
        <div class="species_data"></div>
        <div class="new_species">
            <div class="row">
                <label for="add_plant_name"><?= $T->__("Name") ?></label>
                <input type="text" name="name" id="add_plant_name">
            </div>
            <div class="row">
                <label for="add_plant_url"><?= $T->__("Species URL") ?></label>
                <input type="text" name="url" id="add_plant_url">
                <button type="button" id="btn_load_species"><?= $T->__("Load species") ?></button>
            </div>
        </div>
    </div>
    <div class="buttons">
        <button type="button" class="cancel"><?= $T->__("Cancel") ?></button>
        <button type="submit"><?= $T->__("Add plant") ?></button>
    </div>
</form>
