<form name="add_plant" class="pop-up ajax" action="plant/add" method="POST" enctype="multipart/form-data" style="display:none;">
    <input type="hidden" name="coord_x" />
    <input type="hidden" name="coord_y" />
    <h2><?= $T->__("Add a plant") ?></h2>
    <div class="plant">
        <div class="select" id="slct_species">
            <input type="hidden" name="species_id" />
            <!--<div class="option selected" data-value="null"><?= $T->__("New species") ?></div>-->
            <?php foreach($fm->user->garden->species as $id => $species): ?>
                <div class="option" data-value="<?= $id ?>"><?= $species->get_name() ?></div>
            <?php endforeach; ?>
        </div>
        <div class="row"><button type="button" id="btn_add_species"><?= $T->__("Add new species") ?></button></div>
        <div class="row">
            <label for="add_plant_description"><?= $T->__("Description") ?></label>
            <input type="textarea" name="description" id="add_plant_description">
        </div>
        <div class="row">
            <label for="add_plant_image"><?= $T->__("Image") ?></label>
            <input type="file" accept="image/*" name="image" id="add_plant_image">
        </div>
    </div>
    <div class="species" style="display:none">
        <div class="row"><span class="name"></span></div>
        <div class="row"><img src=""></div>
    </div>
    <div class="buttons">
        <button type="button" class="cancel"><?= $T->__("Cancel") ?></button>
        <button type="submit"><?= $T->__("Add plant") ?></button>
    </div>
</form>
