<form name="edit_species" class="pop-up ajax" action="species/update" method="POST" enctype="multipart/form-data" style="display:none;">
    <input type="hidden" name="species_id" />
    <h2><?= $T->__("Edit species") ?></h2>
    <div class="species">
        <div>
            <h3><?= $T->__("Enter a name or a URL to load a species") ?></h3>
            <div class="row">
                <label for="edit_species_name"><?= $T->__("Name") ?></label>
                <input type="text" name="name" id="edit_species_name">
            </div>
            <div class="row">
                <label for="edit_species_url"><?= $T->__("Species URL") ?></label>
                <input type="text" name="url" id="edit_species_url">
            </div>
            <button type="button" class="btn_load_species"><?= $T->__("Load species") ?></button>
        </div>
        <div class="species_data"></div>
        <input type="hidden" name="species_image">
        <img class="species_image" src="">
        <div class="row">
            <input type="text" class="add_species_data_name"><input type="text" class="add_species_data_value">
            <button type="button" class="btn_add_species_data"><?= $T->__("Add species data") ?></button>
        </div>
    </div>
    <div class="buttons">
        <button type="button" class="cancel"><?= $T->__("Cancel") ?></button>
        <button type="submit"><?= $T->__("Ok") ?></button>
    </div>
</form>
