<form name="edit_plant" class="pop-up" action="controllers/plant.php" method="POST" enctype="multipart/form-data" style="display:none;">
    <input type="hidden" name="action" value="update_plant" />
    <input type="hidden" name="plant_id" />
    <h2><?= $T->__("Edit plant") ?></h2>
    <div class="plant">
        <div class="row"><span class="name"></span></div>
        <div class="row"><label for="edit_plant_description"><?= $T->__("Description") ?></label><input type="textarea" name="description" id="edit_plant_description"></div>
        <div class="row"><label for="edit_plant_image"><?= $T->__("Image") ?></label><input type="file" accept="image/jpeg" name="image" id="edit_plant_image"></div>
    </div>
    <div class="buttons">
        <button type="button" class="cancel"><?= $T->__("Cancel") ?></button>
        <button type="submit"><?= $T->__("Ok") ?></button>
    </div>
</form>
