<div class="garden" style="background-image: url(<?= $fm->user->garden->get_image() ?>)">
    <button type="button" id="btn_zoom_in">+</button>
    <button type="button" id="btn_zoom_out">-</button>
</div>
<?php include("plant_template.phtml") ?>
<?php include("add_plant.phtml") ?>
<?php include("add_species.phtml") ?>
<?php include("edit_plant.phtml") ?>
<?php include("edit_garden.phtml") ?>
<?php include("species_list.phtml") ?>
