<div class="login">
    <form name="login" action="controllers/user.php" method="POST">
        <h2><?= $T->__("Login") ?></h2>
        <input type="hidden" name="action" value="login" />
        <div class="row"><label for="login_name"><?= $T->__("Username") ?></label><input type="text" name="name" id="login_name" /></div>
        <div class="row"><label for="login_password"><?= $T->__("Password") ?></label><input type="password" name="password" id="login_password" /></div>
        <div class="row"><button type="submit"><?= $T->__("Login") ?></button></div>
    </form>
    <form name="register" action="controllers/user.php" method="POST">
        <h2><?= $T->__("Register") ?></h2>
        <input type="hidden" name="action" value="register" />
        <div class="row"><label for="register_name"><?= $T->__("Username") ?></label><input type="text" name="name" id="register_name" /></div>
        <div class="row"><label for="register_password"><?= $T->__("Password") ?></label><input type="password" name="password" id="register_password" /></div>
	      <div class="row"><label for="register_confirm_password"><?= $T->__("Repeat password") ?></label><input type="password" name="confirm_password" id="register_confirm_password" /></div>
	      <div class="row"><button type="submit"><?= $T->__("Register") ?></button></div>
    </form>
</div>
