<h2>Karta över trädgården</h2>
<div class="plant_map" style="background-image: url(<?= $fm->user->garden->get_image() ?>)">
    <?php foreach ($fm->user->garden->plants as $plant): ?>
    <?php include("plant.phtml") ?>
    <?php endforeach; ?>
    <button type="button" id="btn_zoom_in">+</button>
    <button type="button" id="btn_zoom_out">-</button>
</div>
<?php include("add_plant.phtml") ?>
<form name="logout" action="controllers/user.php" method="POST">
    <input type="hidden" name="action" value="logout" />
    <button type="submit"><?= $T->__("Logout") ?></button>
</form>
