<h2>Lista på trädgårdens växter</h2>
<div class="plant_list">
<?php foreach ($fm->user->garden->plants as $plant): ?>
      <?php include("plant.phtml") ?>
<?php endforeach; ?>
</div>
<form name="add_plant" class="pop-up" action="controllers/garden.php" method="POST" enctype="multipart/form-data" style="display:none;">
     <input type="hidden" name="action" value="add_plant" />
     <input type="hidden" name="coord_x" />
     <input type="hidden" name="coord_y" />
     <h2><?= $T->__("Add a plant") ?></h2>
     <div class="plant">
          <div class="row"><label for="add_plant_description"><?= $T->__("Description") ?></label><input type="textarea" name="description" id="add_plant_description"></div>
          <div class="row"><label for="add_plant_image"><?= $T->__("Image") ?></label><input type="file" accept="image/jpeg" name="image" id="add_plant_image"></div>
     </div>
     <div class="species">
          <input type="hidden" name="species_id" />
          <div class="species_data">
               <div class="row"><label for="add_plant_name"><?= $T->__("Name") ?></label><input type="text" name="name" id="add_plant_name"></div>
          </div>
          <div class="row">
               <label for="add_plant_url"><?= $T->__("Species URL") ?></label><input type="text" name="url" id="add_plant_url">
               <button type="button" id="btn_load_species"><?= $T->__("Load species") ?></button>
          </div>
     </div>
     <div class="buttons">
          <button type="button" class="cancel"><?= $T->__("Cancel") ?></button>
          <button type="submit"><?= $T->__("Add plant") ?></button>
     </div>
</form>
<form name="logout" action="controllers/user.php" method="POST">
     <input type="hidden" name="action" value="logout" />
     <button type="submit"><?= $T->__("Logout") ?></button>
</form>