<div class="plant" id="plant_template" style="display:none">
    <div class="name"></div>
    <div class="description"></div>
    <img src="">
    <div class="data"></div>
    <div class="buttons">
        <button class="btn_edit"><?= $T->__("Edit") ?></button>
        <button class="btn_move"><?= $T->__("Move") ?></button>
        <button class="btn_remove"><?= $T->__("Remove") ?></button>
    </div>
</div>
